### ISSUE TITLE
What is the pre-warming for?

### ISSUE THREAD

**Issue by chrishkchris** [cybertronai/imagenet18_old#25]
I am doing research and development for distributed deep learning, so your code is very interesting to me. 

I noticed the code needs to run train.py for two times, while the first time is pre-warming.

What is pre-warming for? How is the pre-warming done and how long?

Is it the case that the inter node all-reduce could be down with large number of instances without the pre-warming?

Thanks a lot!

**Comment by yaroslavvb** [comment]
Pre-warming is only needed if you care about 18 minutes. Without pre-warming it'll maybe around 20 minutes. What happens is that if you run the experiment once, disk reads are cached, so second time is faster.

BTW, since I'm no longer at diux I can't make changes to this repo, I do further changes fixes at https://github.com/yaroslavvb/imagenet18
